/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package transaksi;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import table_model.supplier;

/**
 *
 * @author Bagus
 */
public class RincianDataPenjualan extends javax.swing.JFrame {
    private String idPenjualan;
    public String IDPelanggan, NamaPelanggan;
    public String IDBarang, NamaBarang, KategoriBarang, HargaBarang;
    
    private DefaultTableModel tabmode;
    Object[] Baris = {"Id Barang", "Nama Barang", "Kategori", "Harga", "QTY", "Total Harga"};

    /**
     * Creates new form RincianDataPenjualan
     */
    public RincianDataPenjualan() {
        initComponents();
        
        tabmode = new DefaultTableModel(null, Baris);
        tableTransaksi.setModel(tabmode);
        tableTransaksi.fixTable(jScrollPane1);
    }
    
    public void setData(String id) {
        this.idPenjualan = id;
        
        Connection conn = new koneksi().getConnection();
        
        String query1 = "SELECT p.id, p.nama_pelanggan, pjl.id, pjl.tanggal_jual, pjl.status FROM penjualan AS pjl " +
                "JOIN pelanggan AS p ON pjl.id_pelanggan = p.id " +
                "WHERE pjl.id = ?";
        String query2 = "SELECT b.id, b.nama, b.kategori, b.harga, dpjl.kuantitas, dpjl.total_harga " +
                "FROM detail_penjualan AS dpjl " +
                "JOIN barang AS b ON dpjl.id_barang = b.id " +
                "WHERE dpjl.id_penjualan = ?";
        
        try {
            PreparedStatement stat1 = conn.prepareStatement(query1);
            stat1.setString(1, idPenjualan);
            ResultSet hasil1 = stat1.executeQuery();
            
            while(hasil1.next()) {
                idPelanggan.setText(hasil1.getString(1));
                namaPelanggan.setText(hasil1.getString(2));
                idNota.setText(hasil1.getString(3));
                tanggalNota.setDate(hasil1.getDate(4));
                
                if(hasil1.getString(5).equals("Lunas")) {
                    status.setSelectedIndex(0);
                } else {
                    status.setSelectedIndex(1);
                }
            }
            
            PreparedStatement stat2 = conn.prepareStatement(query2);
            stat2.setString(1, idPenjualan);
            stat2.executeQuery();
            ResultSet hasil2 = stat2.executeQuery();
            
            while(hasil2.next()) {
                tabmode.addRow(new Object[]{
                    hasil2.getString(1),
                    hasil2.getString(2),
                    hasil2.getString(3),
                    hasil2.getString(4),
                    hasil2.getString(5),
                    hasil2.getString(6),
                });
            }
            conn.close();
            stat1.close();
            stat2.close();
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal ditampilkan, pesan error: " + e);
            Logger.getLogger(supplier.class.getName()).log(Level.SEVERE, null, e);
        }
        
        hitung();
    }
    
    public void pelangganTerpilih() {
        PopUpPelanggan Pp = new PopUpPelanggan();
        Pp.rincianDataPenjualan = this;
        idPelanggan.setText(IDPelanggan);
        namaPelanggan.setText(NamaPelanggan);
    }
    
    public void barangTerpilih() {
        PopUpBarang Pb = new PopUpBarang();
        Pb.rincianDataPenjualan = this;
        idBarang.setText(IDBarang);
        namaBarang.setText(NamaBarang);
        kategori.setText(KategoriBarang);
        harga.setText(HargaBarang);
    }
    
    public void hitung() {
        int total = 0;
        for (int i = 0; i < tableTransaksi.getRowCount(); i++) {
            float amount = Float.valueOf(tableTransaksi.getValueAt(i, 5).toString());
            total += amount;
        }
        totalTransaksi.setText(Integer.toString(total));
    }
    
    public void kosong() {
        idBarang.setText("");
        namaBarang.setText("");
        kategori.setText("");
        harga.setText("");
        kuantitas.setText("");
        totalHarga.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        roundedPanel1 = new custom_palette.RoundedPanel();
        jLabel3 = new javax.swing.JLabel();
        idNota = new custom_palette.RoundedTextField();
        roundedPanel2 = new custom_palette.RoundedPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        namaPelanggan = new custom_palette.RoundedTextField();
        idPelanggan = new custom_palette.RoundedTextField();
        cariPelangganButton = new custom_palette.RoundedButton();
        jLabel4 = new javax.swing.JLabel();
        roundedPanel3 = new custom_palette.RoundedPanel();
        cariBarangButton = new custom_palette.RoundedButton();
        namaBarang = new custom_palette.RoundedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        harga = new custom_palette.RoundedTextField();
        kuantitas = new custom_palette.RoundedTextField();
        hitungButton = new custom_palette.RoundedButton();
        totalHarga = new custom_palette.RoundedTextField();
        tambahBarangButton = new custom_palette.RoundedButton();
        hapusBarangButton = new custom_palette.RoundedButton();
        kosongkanButton = new custom_palette.RoundedButton();
        jLabel16 = new javax.swing.JLabel();
        kategori = new custom_palette.RoundedTextField();
        idBarang = new custom_palette.RoundedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new custom_palette.CustomTable();
        jLabel14 = new javax.swing.JLabel();
        totalTransaksi = new custom_palette.RoundedTextField();
        jLabel15 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        cancelButton = new custom_palette.RoundedButton();
        tanggalNota = new com.toedter.calendar.JDateChooser();
        removeButton = new custom_palette.RoundedButton();
        editButton = new custom_palette.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(242, 241, 235));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo-penjualan.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 24, -1, -1));

        jLabel2.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(142, 175, 148));
        jLabel2.setText("Manajemen Penjualan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 34, 260, 30));

        jSeparator1.setBackground(new java.awt.Color(136, 171, 142));
        jSeparator1.setForeground(new java.awt.Color(136, 171, 142));
        jSeparator1.setPreferredSize(new java.awt.Dimension(291, 10));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 66, -1, -1));

        roundedPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel1.setForeground(new java.awt.Color(255, 255, 255));
        roundedPanel1.setCornerRadius(40);
        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Inter", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(175, 200, 173));
        jLabel3.setText("Rincian Data Penjualan");
        roundedPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 54, 390, 37));

        idNota.setEditable(false);
        idNota.setBackground(new java.awt.Color(175, 200, 173));
        idNota.setForeground(new java.awt.Color(238, 231, 218));
        idNota.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idNota.setCornerRadius(10);
        idNota.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        idNota.setLineColor(new java.awt.Color(175, 200, 173));
        roundedPanel1.add(idNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 62, 130, 26));

        roundedPanel2.setBackground(new java.awt.Color(136, 171, 142));
        roundedPanel2.setForeground(new java.awt.Color(136, 171, 142));
        roundedPanel2.setCornerRadius(20);
        roundedPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Inter", 1, 32)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 231, 218));
        jLabel5.setText("Data Pelanggan");
        roundedPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 14, 253, 39));

        jLabel6.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(238, 231, 218));
        jLabel6.setText("ID Pelanggan");
        roundedPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 77, -1, -1));

        jLabel7.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(238, 231, 218));
        jLabel7.setText("Nama Pelanggan");
        roundedPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 122, -1, -1));

        namaPelanggan.setBackground(new java.awt.Color(238, 231, 218));
        namaPelanggan.setCornerRadius(10);
        namaPelanggan.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        namaPelanggan.setLineColor(new java.awt.Color(238, 231, 218));
        roundedPanel2.add(namaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 122, 195, -1));

        idPelanggan.setBackground(new java.awt.Color(238, 231, 218));
        idPelanggan.setCornerRadius(10);
        idPelanggan.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        idPelanggan.setLineColor(new java.awt.Color(238, 231, 218));
        roundedPanel2.add(idPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 77, 110, -1));

        cariPelangganButton.setForeground(new java.awt.Color(136, 171, 142));
        cariPelangganButton.setText("Cari");
        cariPelangganButton.setColor(new java.awt.Color(238, 231, 218));
        cariPelangganButton.setColorClick(new java.awt.Color(190, 184, 174));
        cariPelangganButton.setColorOver(new java.awt.Color(214, 207, 196));
        cariPelangganButton.setcornerRadius(10);
        cariPelangganButton.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        cariPelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariPelangganButtonActionPerformed(evt);
            }
        });
        roundedPanel2.add(cariPelangganButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 75, -1, -1));

        roundedPanel1.add(roundedPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 206, 424, 179));

        jLabel4.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(175, 200, 173));
        jLabel4.setText("Tanggal");
        roundedPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 66, 90, -1));

        roundedPanel3.setBackground(new java.awt.Color(136, 171, 142));
        roundedPanel3.setForeground(new java.awt.Color(136, 171, 142));
        roundedPanel3.setCornerRadius(20);
        roundedPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cariBarangButton.setForeground(new java.awt.Color(136, 171, 142));
        cariBarangButton.setText("Cari");
        cariBarangButton.setColor(new java.awt.Color(238, 231, 218));
        cariBarangButton.setColorClick(new java.awt.Color(190, 184, 174));
        cariBarangButton.setColorOver(new java.awt.Color(214, 207, 196));
        cariBarangButton.setcornerRadius(10);
        cariBarangButton.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        cariBarangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBarangButtonActionPerformed(evt);
            }
        });
        roundedPanel3.add(cariBarangButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 82, -1, -1));

        namaBarang.setBackground(new java.awt.Color(238, 231, 218));
        namaBarang.setCornerRadius(10);
        namaBarang.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        namaBarang.setLineColor(new java.awt.Color(238, 231, 218));
        roundedPanel3.add(namaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 119, 210, -1));

        jLabel8.setFont(new java.awt.Font("Inter", 1, 32)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(238, 231, 218));
        jLabel8.setText("Data Barang");
        roundedPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 16, -1, -1));

        jLabel9.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(238, 231, 218));
        jLabel9.setText("ID Barang");
        roundedPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 83, -1, -1));

        jLabel10.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(238, 231, 218));
        jLabel10.setText("Nama Barang");
        roundedPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 119, -1, -1));

        jLabel11.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(238, 231, 218));
        jLabel11.setText("Harga");
        roundedPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 191, -1, -1));

        jLabel12.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(238, 231, 218));
        jLabel12.setText("Kuantitas");
        roundedPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 227, -1, -1));

        jLabel13.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(238, 231, 218));
        jLabel13.setText("Total Harga");
        roundedPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 263, -1, -1));

        harga.setBackground(new java.awt.Color(238, 231, 218));
        harga.setCornerRadius(10);
        harga.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        harga.setLineColor(new java.awt.Color(238, 231, 218));
        roundedPanel3.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 191, 210, -1));

        kuantitas.setBackground(new java.awt.Color(238, 231, 218));
        kuantitas.setCornerRadius(10);
        kuantitas.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        kuantitas.setLineColor(new java.awt.Color(238, 231, 218));
        roundedPanel3.add(kuantitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 227, 85, -1));

        hitungButton.setForeground(new java.awt.Color(136, 171, 142));
        hitungButton.setText("Hitung Total");
        hitungButton.setColor(new java.awt.Color(238, 231, 218));
        hitungButton.setColorClick(new java.awt.Color(190, 184, 174));
        hitungButton.setColorOver(new java.awt.Color(214, 207, 196));
        hitungButton.setcornerRadius(10);
        hitungButton.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        hitungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungButtonActionPerformed(evt);
            }
        });
        roundedPanel3.add(hitungButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 226, -1, -1));

        totalHarga.setBackground(new java.awt.Color(238, 231, 218));
        totalHarga.setCornerRadius(10);
        totalHarga.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        totalHarga.setLineColor(new java.awt.Color(238, 231, 218));
        roundedPanel3.add(totalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 263, 210, -1));

        tambahBarangButton.setForeground(new java.awt.Color(136, 171, 142));
        tambahBarangButton.setText("Tambah Barang");
        tambahBarangButton.setColor(new java.awt.Color(238, 231, 218));
        tambahBarangButton.setColorClick(new java.awt.Color(190, 184, 174));
        tambahBarangButton.setColorOver(new java.awt.Color(214, 207, 196));
        tambahBarangButton.setcornerRadius(10);
        tambahBarangButton.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        tambahBarangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBarangButtonActionPerformed(evt);
            }
        });
        roundedPanel3.add(tambahBarangButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 307, 140, -1));

        hapusBarangButton.setForeground(new java.awt.Color(136, 171, 142));
        hapusBarangButton.setColor(new java.awt.Color(238, 231, 218));
        hapusBarangButton.setColorClick(new java.awt.Color(190, 184, 174));
        hapusBarangButton.setColorOver(new java.awt.Color(214, 207, 196));
        hapusBarangButton.setcornerRadius(10);
        hapusBarangButton.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        hapusBarangButton.setLabel("Hapus Barang");
        hapusBarangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBarangButtonActionPerformed(evt);
            }
        });
        roundedPanel3.add(hapusBarangButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 307, 147, -1));

        kosongkanButton.setForeground(new java.awt.Color(136, 171, 142));
        kosongkanButton.setText("Kosongkan");
        kosongkanButton.setColor(new java.awt.Color(238, 231, 218));
        kosongkanButton.setColorClick(new java.awt.Color(190, 184, 174));
        kosongkanButton.setColorOver(new java.awt.Color(214, 207, 196));
        kosongkanButton.setcornerRadius(10);
        kosongkanButton.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        kosongkanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kosongkanButtonActionPerformed(evt);
            }
        });
        roundedPanel3.add(kosongkanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 307, 147, -1));

        jLabel16.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(238, 231, 218));
        jLabel16.setText("Kategori");
        roundedPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 155, -1, -1));

        kategori.setBackground(new java.awt.Color(238, 231, 218));
        kategori.setCornerRadius(10);
        kategori.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        kategori.setLineColor(new java.awt.Color(238, 231, 218));
        roundedPanel3.add(kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 155, 210, -1));

        idBarang.setBackground(new java.awt.Color(238, 231, 218));
        idBarang.setCornerRadius(10);
        idBarang.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        idBarang.setLineColor(new java.awt.Color(238, 231, 218));
        roundedPanel3.add(idBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 83, 130, -1));

        roundedPanel1.add(roundedPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 106, 562, 359));

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableTransaksi);

        roundedPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 482, 1049, 166));

        jLabel14.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(175, 200, 173));
        jLabel14.setText("Total Transaksi");
        roundedPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 682, -1, -1));

        totalTransaksi.setBackground(new java.awt.Color(175, 200, 173));
        totalTransaksi.setForeground(new java.awt.Color(238, 231, 218));
        totalTransaksi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalTransaksi.setCornerRadius(10);
        totalTransaksi.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        totalTransaksi.setLineColor(new java.awt.Color(175, 200, 173));
        roundedPanel1.add(totalTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 685, 180, -1));

        jLabel15.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(175, 200, 173));
        jLabel15.setText("Status");
        roundedPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 682, -1, -1));

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunas", "Belum Lunas" }));
        roundedPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 685, 195, -1));

        cancelButton.setForeground(new java.awt.Color(136, 171, 142));
        cancelButton.setText("X Batal");
        cancelButton.setColor(new java.awt.Color(238, 231, 218));
        cancelButton.setColorClick(new java.awt.Color(190, 184, 174));
        cancelButton.setColorOver(new java.awt.Color(214, 207, 196));
        cancelButton.setcornerRadius(10);
        cancelButton.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        roundedPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(987, 673, 125, 39));
        roundedPanel1.add(tanggalNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(957, 68, 147, 22));

        removeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo-trash.png"))); // NOI18N
        removeButton.setColor(new java.awt.Color(255, 75, 75));
        removeButton.setColorClick(new java.awt.Color(204, 60, 60));
        removeButton.setColorOver(new java.awt.Color(229, 67, 67));
        removeButton.setcornerRadius(10);
        removeButton.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        roundedPanel1.add(removeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 673, 83, 41));

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo-write.png"))); // NOI18N
        editButton.setColor(new java.awt.Color(247, 147, 39));
        editButton.setColorClick(new java.awt.Color(197, 117, 31));
        editButton.setColorOver(new java.awt.Color(222, 132, 35));
        editButton.setcornerRadius(15);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        roundedPanel1.add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 673, 83, 41));

        jPanel1.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 72, 1178, 729));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 832, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cariPelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariPelangganButtonActionPerformed
        PopUpPelanggan Pp = new PopUpPelanggan();
        Pp.rincianDataPenjualan = this;
        Pp.setVisible(true);
        Pp.setResizable(false);
    }//GEN-LAST:event_cariPelangganButtonActionPerformed

    private void cariBarangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBarangButtonActionPerformed
        PopUpBarang Pb = new PopUpBarang();
        Pb.rincianDataPenjualan = this;
        Pb.setVisible(true);
        Pb.setResizable(false);
    }//GEN-LAST:event_cariBarangButtonActionPerformed

    private void hitungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungButtonActionPerformed
        float intHarga, intKuantitas, jumlah;
        intHarga = Float.parseFloat(harga.getText());
        intKuantitas = Float.parseFloat(kuantitas.getText());
        jumlah = intHarga * intKuantitas;
        totalHarga.setText(String.valueOf(jumlah));
    }//GEN-LAST:event_hitungButtonActionPerformed

    private void tambahBarangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBarangButtonActionPerformed
        Connection conn = new koneksi().getConnection();
        
        try {
            String kolomIdBarang = idBarang.getText();
            String kolomNamaBarang = namaBarang.getText();
            String kolomKategori = kategori.getText();
            float kolomHarga = Float.parseFloat(harga.getText());
            int kolomKuantitas = Integer.parseInt(kuantitas.getText());
            float kolomTotalHarga = Float.parseFloat(totalHarga.getText());
            tabmode.addRow(new Object[]{kolomIdBarang, kolomNamaBarang, kolomKategori, kolomHarga, kolomKuantitas, kolomTotalHarga});
            tableTransaksi.setModel(tabmode);
            
            String query = "insert into detail_penjualan(id_penjualan, id_barang, nama_barang, kategori, harga, kuantitas, total_harga) values(?,?,?,?,?,?,?)";
            
            PreparedStatement stat = conn.prepareStatement(query);
            stat.setString(1, idPenjualan);
            stat.setInt(2, Integer.parseInt(kolomIdBarang));
            stat.setString(3, kolomNamaBarang);
            stat.setString(4, kolomKategori);
            stat.setFloat(5, kolomHarga);
            stat.setInt(6, kolomKuantitas);
            stat.setFloat(7, kolomTotalHarga);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil ditambah");
        } catch (Exception e) {
            System.out.println("Error : " + e);
        }
        
        try {
            String query = "update barang set stok = stok - ? where id = ?";
            PreparedStatement stat = conn.prepareStatement(query);
            stat.setInt(1, Integer.parseInt(kuantitas.getText()));
            stat.setString(2, idBarang.getText());
            stat.executeUpdate();
            
            conn.close();
            stat.close();
        } catch (Exception e) {
            System.out.println("Error : " + e);
        }
        
        kosong();
        hitung();
    }//GEN-LAST:event_tambahBarangButtonActionPerformed

    private void hapusBarangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBarangButtonActionPerformed
        Connection conn = new koneksi().getConnection();
        
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data barang ini?", "Hapus Data Barang", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            int index = tableTransaksi.getSelectedRow();
            int kolomIdBarang = Integer.parseInt(tableTransaksi.getValueAt(index, 0).toString());
            int kolomKuantitas = Integer.parseInt(tableTransaksi.getValueAt(index, 4).toString());

            try {
                String query = "delete from detail_penjualan where id_penjualan = ? and id_barang = ?";

                PreparedStatement stat = conn.prepareStatement(query);
                stat.setString(1, idPenjualan);
                stat.setInt(2, kolomIdBarang);
                stat.executeUpdate();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "data gagal dihapus, pesan error: " + e);
            }
            
            try {
                String query = "update barang set stok = stok + ? where id = ?";

                PreparedStatement stat = conn.prepareStatement(query);
                stat.setInt(1, kolomKuantitas);
                stat.setInt(2, kolomIdBarang);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");

                conn.close();
                stat.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "data gagal dihapus, pesan error: " + e);
            }

            tabmode.removeRow(index);
            tableTransaksi.setModel(tabmode);
            hitung();
        }
    }//GEN-LAST:event_hapusBarangButtonActionPerformed

    private void kosongkanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kosongkanButtonActionPerformed
        kosong();
    }//GEN-LAST:event_kosongkanButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        JFrame Penjualan = new table_model.penjualan();
        Penjualan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        Connection conn = new koneksi().getConnection();

        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data penjualan ini?", "Hapus Data Penjualan", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            String sql1 = "delete from detail_penjualan where id_penjualan = ?";
            String sql2 = "delete from penjualan where id = ?";
            String sql3 = "update barang set stok = stok + ? where id = ?";
                       
            try {
                int t = tableTransaksi.getRowCount();
            
                for (int i = 0; i < t; i++) {
                    String kolomIdBarang = tableTransaksi.getValueAt(i, 0).toString();
                    int kolomKuantitas = Integer.parseInt(tableTransaksi.getValueAt(i, 4).toString());
                    
                    PreparedStatement stat = conn.prepareStatement(sql3);
                    stat.setInt(1, kolomKuantitas);
                    stat.setString(2, kolomIdBarang);
                    stat.executeUpdate();
                }
                                
                PreparedStatement stat1 = conn.prepareStatement(sql1);
                stat1.setString(1, idPenjualan);
                stat1.executeUpdate();
                
                PreparedStatement stat2 = conn.prepareStatement(sql2);
                stat2.setString(1, idPenjualan);
                stat2.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");

                stat1.close();
                stat2.close();
                conn.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "data gagal dihapus, pesan error: " + e);
            }
            
            JFrame penjualan = new table_model.penjualan();
            penjualan.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        Connection conn = new koneksi().getConnection();

        try {
            String sql = "update penjualan set tanggal_jual = ?, status = ? where id = ?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setDate(1, new java.sql.Date(tanggalNota.getDate().getTime()));
            stat.setString(2, status.getSelectedItem().toString());
            stat.setString(3, idNota.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            
            conn.close();
            stat.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal diubah, pesan error: " + e);
        }
    }//GEN-LAST:event_editButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RincianDataPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RincianDataPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RincianDataPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RincianDataPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RincianDataPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom_palette.RoundedButton cancelButton;
    private custom_palette.RoundedButton cariBarangButton;
    private custom_palette.RoundedButton cariPelangganButton;
    private custom_palette.RoundedButton editButton;
    private custom_palette.RoundedButton hapusBarangButton;
    private custom_palette.RoundedTextField harga;
    private custom_palette.RoundedButton hitungButton;
    private custom_palette.RoundedTextField idBarang;
    private custom_palette.RoundedTextField idNota;
    private custom_palette.RoundedTextField idPelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private custom_palette.RoundedTextField kategori;
    private custom_palette.RoundedButton kosongkanButton;
    private custom_palette.RoundedTextField kuantitas;
    private custom_palette.RoundedTextField namaBarang;
    private custom_palette.RoundedTextField namaPelanggan;
    private custom_palette.RoundedButton removeButton;
    private custom_palette.RoundedPanel roundedPanel1;
    private custom_palette.RoundedPanel roundedPanel2;
    private custom_palette.RoundedPanel roundedPanel3;
    private javax.swing.JComboBox<String> status;
    private custom_palette.CustomTable tableTransaksi;
    private custom_palette.RoundedButton tambahBarangButton;
    private com.toedter.calendar.JDateChooser tanggalNota;
    private custom_palette.RoundedTextField totalHarga;
    private custom_palette.RoundedTextField totalTransaksi;
    // End of variables declaration//GEN-END:variables
}
