/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package transaksi;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import koneksi.koneksi;

/**
 *
 * @author Bagus
 */
public class TambahPembelian extends javax.swing.JFrame {
    
  
    /**
     * Creates new form TambahKaryawan
     */
    public TambahPembelian() {
        initComponents();
        populateComboBoxes();
        kosong();
    } 
    
    protected void kosong() {
        transaksi.setText("");
        cbnamasupplier.setSelectedItem(null);
        cbnamabarang.setSelectedItem(null);
        kuantitas.setText("");
        tanggal_beli.setDate(new Date());
        status.setSelectedItem("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        roundedPanel1 = new custom_palette.RoundedPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        transaksi = new custom_palette.RoundedTextField();
        tanggal_beli = new com.toedter.calendar.JDateChooser();
        addDataButton = new custom_palette.RoundedButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        kuantitas = new custom_palette.RoundedTextField();
        jLabel12 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        cbnamabarang = new javax.swing.JComboBox<>();
        cbnamasupplier = new javax.swing.JComboBox<>();
        cancelButton = new custom_palette.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(242, 241, 235));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo-pembelian2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 38, -1, -1));

        jLabel2.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(142, 175, 148));
        jLabel2.setText("Manajemen Pembelian");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 47, 290, 40));

        roundedPanel1.setBackground(new java.awt.Color(136, 171, 142));
        roundedPanel1.setForeground(new java.awt.Color(136, 171, 142));
        roundedPanel1.setCornerRadius(30);
        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Inter", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 231, 218));
        jLabel3.setText("Tambah Data Pembelian");
        roundedPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 38, 420, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo-penjualan2.png"))); // NOI18N
        roundedPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 148, -1, -1));

        jLabel5.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 231, 218));
        jLabel5.setText("Kuantitas");
        roundedPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 140, -1));

        jLabel6.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(238, 231, 218));
        jLabel6.setText("Status");
        roundedPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 130, -1));

        jLabel9.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(238, 231, 218));
        jLabel9.setText("Tanggal Beli");
        roundedPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 160, 20));

        transaksi.setBackground(new java.awt.Color(238, 231, 218));
        transaksi.setForeground(new java.awt.Color(0, 0, 0));
        transaksi.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        transaksi.setLineColor(new java.awt.Color(238, 231, 218));
        roundedPanel1.add(transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 232, -1));

        tanggal_beli.setBackground(new java.awt.Color(238, 231, 218));
        tanggal_beli.setForeground(new java.awt.Color(0, 0, 0));
        tanggal_beli.setDateFormatString("yyyy-MM-dd");
        tanggal_beli.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        tanggal_beli.setOpaque(false);
        tanggal_beli.setPreferredSize(new java.awt.Dimension(232, 22));
        roundedPanel1.add(tanggal_beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, -1, -1));

        addDataButton.setForeground(new java.awt.Color(136, 171, 142));
        addDataButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/material-symbols_tambah.png"))); // NOI18N
        addDataButton.setText("Tambah");
        addDataButton.setColor(new java.awt.Color(238, 231, 218));
        addDataButton.setColorClick(new java.awt.Color(190, 184, 174));
        addDataButton.setColorOver(new java.awt.Color(214, 207, 196));
        addDataButton.setcornerRadius(15);
        addDataButton.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        addDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDataButtonActionPerformed(evt);
            }
        });
        roundedPanel1.add(addDataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 508, 125, 43));

        jLabel10.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(238, 231, 218));
        jLabel10.setText("Nama Supplier");
        roundedPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 140, -1));

        jLabel11.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(238, 231, 218));
        jLabel11.setText("Nama Barang");
        roundedPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 140, -1));

        kuantitas.setBackground(new java.awt.Color(238, 231, 218));
        kuantitas.setForeground(new java.awt.Color(0, 0, 0));
        kuantitas.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        kuantitas.setLineColor(new java.awt.Color(238, 231, 218));
        roundedPanel1.add(kuantitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 232, -1));

        jLabel12.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(238, 231, 218));
        jLabel12.setText("Total Transaksi");
        roundedPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 130, -1));

        status.setBackground(new java.awt.Color(248, 248, 248));
        status.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        status.setForeground(new java.awt.Color(0, 0, 0));
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunas", "Belum Lunas" }));
        status.setOpaque(true);
        status.setPreferredSize(new java.awt.Dimension(118, 26));
        roundedPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 160, -1));

        cbnamabarang.setBackground(new java.awt.Color(248, 248, 248));
        cbnamabarang.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        cbnamabarang.setForeground(new java.awt.Color(0, 0, 0));
        cbnamabarang.setOpaque(true);
        cbnamabarang.setPreferredSize(new java.awt.Dimension(118, 26));
        roundedPanel1.add(cbnamabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 230, -1));

        cbnamasupplier.setBackground(new java.awt.Color(248, 248, 248));
        cbnamasupplier.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        cbnamasupplier.setForeground(new java.awt.Color(0, 0, 0));
        cbnamasupplier.setOpaque(true);
        cbnamasupplier.setPreferredSize(new java.awt.Dimension(118, 26));
        roundedPanel1.add(cbnamasupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 230, -1));

        jPanel1.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 118, 1006, 583));

        cancelButton.setForeground(new java.awt.Color(238, 231, 218));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/material-symbols_batal.png"))); // NOI18N
        cancelButton.setText("Batal");
        cancelButton.setColor(new java.awt.Color(136, 171, 142));
        cancelButton.setColorClick(new java.awt.Color(108, 136, 113));
        cancelButton.setColorOver(new java.awt.Color(122, 153, 127));
        cancelButton.setcornerRadius(15);
        cancelButton.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1118, 744, 130, 49));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 832));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDataButtonActionPerformed
        Connection conn = new koneksi().getConnection();
        
        try{
            String sql = "insert into pembelian(id_supplier, id_barang, tanggal_beli, kuantitas, total_harga, status) values (?,?,?,?,?,?)";
            
            PreparedStatement stat = conn.prepareStatement(sql);
            String selectedPelanggan = (String) cbnamasupplier.getSelectedItem();
            int idPelanggan = Integer.parseInt(selectedPelanggan.split(" - ")[0]);
            String selectedBarang = (String) cbnamabarang.getSelectedItem();
            int idBarang = Integer.parseInt(selectedBarang.split(" - ")[0]);

            stat.setInt(1, idPelanggan);
            stat.setInt(2, idBarang);
            stat.setDate(3, new java.sql.Date(tanggal_beli.getDate().getTime()));
            stat.setInt(4, Integer.parseInt(kuantitas.getText()));
            stat.setDouble(5, Double.parseDouble(transaksi.getText()));
            stat.setString(6, status.getSelectedItem().toString());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal disimpan, pesan error: "+e);
        }
        
        try {
            String selectedBarang = (String) cbnamabarang.getSelectedItem();
            int idBarang = Integer.parseInt(selectedBarang.split(" - ")[0]);
            int Kuantitas = Integer.parseInt(kuantitas.getText());
            
            String query2 = "update barang set stok = stok + ? where id = ?";
            
            PreparedStatement stat = conn.prepareStatement(query2);
            stat.setInt(1, Kuantitas);
            stat.setInt(2, idBarang);
            stat.executeUpdate();
            
            kosong();
            conn.close();
            stat.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "gagal update stok barang: "+e);
        }
    }//GEN-LAST:event_addDataButtonActionPerformed

    
    private void populateComboBoxes() {
        Connection conn = new koneksi().getConnection();
    
        String pelangganSql = "SELECT id, nama_supplier FROM suppliers";
        String barangSql = "SELECT id, kode_barang, nama FROM barang";
    
        try {
            // Populate pelanggan ComboBox
            PreparedStatement pelangganStat = conn.prepareStatement(pelangganSql);
            ResultSet pelangganRs = pelangganStat.executeQuery();
            while (pelangganRs.next()) {
                int id = pelangganRs.getInt("id");
                String namaPelanggan = pelangganRs.getString("nama_supplier");
                cbnamasupplier.addItem(id + " - " + namaPelanggan);
            }
        
            // Populate barang ComboBox
            PreparedStatement barangStat = conn.prepareStatement(barangSql);
            ResultSet barangRs = barangStat.executeQuery();
            while (barangRs.next()) {
                int id = barangRs.getInt("id");
                String kodeBarang = barangRs.getString("kode_barang");
                String namaBarang = barangRs.getString("nama");
                cbnamabarang.addItem(id + " - " + namaBarang + " - " + kodeBarang);
            }
        
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace(); // Tambahkan ini untuk melihat detail error di konsol
            JOptionPane.showMessageDialog(null, "Error loading data: " + e.getMessage());
        }
    }

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        try {
            // Mengatur look and feel menjadi Nimbus
            UIManager.LookAndFeelInfo[] looks = UIManager.getInstalledLookAndFeels();
            for (UIManager.LookAndFeelInfo look : looks) {
                if ("Nimbus".equals(look.getName())) {
                    UIManager.setLookAndFeel(look.getClassName());
                    break;
                }
            }

            // Buat objek JFrame baru
            JFrame formPembelian = new table_model.pembelian();

            // Tampilkan JFrame baru
            formPembelian.setVisible(true);

            // Tutup jendela saat ini
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException ignored) {
            Toolkit.getDefaultToolkit().beep();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            ex.printStackTrace();
            return;
        }
        
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TambahKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TambahKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TambahKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TambahKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahPembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom_palette.RoundedButton addDataButton;
    private custom_palette.RoundedButton cancelButton;
    private javax.swing.JComboBox<String> cbnamabarang;
    private javax.swing.JComboBox<String> cbnamasupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private custom_palette.RoundedTextField kuantitas;
    private custom_palette.RoundedPanel roundedPanel1;
    private javax.swing.JComboBox<String> status;
    private com.toedter.calendar.JDateChooser tanggal_beli;
    private custom_palette.RoundedTextField transaksi;
    // End of variables declaration//GEN-END:variables
}
