/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import koneksi.koneksi;

/**
 *
 * @author sabdha
 */
public class RincianDataBarang extends javax.swing.JFrame {
 private int id;
    /**
     * Creates new form UbahBarang
     */
    public RincianDataBarang() {
        initComponents();
        cbKategori.addItem("frame");
        cbKategori.addItem("lensa");
        cbKategori.addItem("aksesoris");
//        kosong();
    }
//protected void kosong(){ 
//          txtkode.setText(""); 
//          txtnama.setText(""); 
//          cbKategori.setSelectedItem(""); 
//          txtharga.setText(""); 
//          txtstok.setText(""); 
//      }
public void setData(int id, String[] values) {
       this.id = id;
         
        txtkode.setText(values[0]);
        txtnama.setText(values[1]);
        cbKategori.setSelectedItem(values[2]);
        txtharga.setText(values[3]);
        txtstok.setText(values[4]);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        roundedPanel1 = new custom_palette.RoundedPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtkode = new custom_palette.RoundedTextField();
        txtnama = new custom_palette.RoundedTextField();
        txtharga = new custom_palette.RoundedTextField();
        txtstok = new custom_palette.RoundedTextField();
        btnubah = new custom_palette.RoundedButton();
        btnHapus = new custom_palette.RoundedButton();
        cbKategori = new javax.swing.JComboBox<>();
        cancelButton = new custom_palette.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(242, 241, 235));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 832));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo-box2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(136, 171, 142));
        jLabel2.setText("Manajemen Inventaris");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 37, 223, 25));

        jSeparator1.setBackground(new java.awt.Color(136, 171, 142));
        jSeparator1.setForeground(new java.awt.Color(136, 171, 142));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 72, 291, 10));

        roundedPanel1.setBackground(new java.awt.Color(136, 171, 142));
        roundedPanel1.setForeground(new java.awt.Color(136, 171, 142));
        roundedPanel1.setCornerRadius(15);
        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/amico1.png"))); // NOI18N
        roundedPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 121, 392, 342));

        jLabel4.setBackground(new java.awt.Color(238, 231, 218));
        jLabel4.setFont(new java.awt.Font("Inter", 1, 32)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 231, 218));
        jLabel4.setText("RINCIAN DATA BARANG");
        roundedPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 38, 412, 38));

        jLabel5.setBackground(new java.awt.Color(238, 231, 218));
        jLabel5.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 231, 218));
        jLabel5.setText("Kode Barang");
        roundedPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 171, 111, 21));

        jLabel6.setBackground(new java.awt.Color(238, 231, 218));
        jLabel6.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(238, 231, 218));
        jLabel6.setText("Nama Barang ");
        roundedPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 236, 111, 21));

        jLabel7.setBackground(new java.awt.Color(238, 231, 218));
        jLabel7.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(238, 231, 218));
        jLabel7.setText("Kategori");
        roundedPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 301, 111, 21));

        jLabel8.setBackground(new java.awt.Color(238, 231, 218));
        jLabel8.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(238, 231, 218));
        jLabel8.setText("Harga");
        roundedPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 366, 111, 21));

        jLabel9.setBackground(new java.awt.Color(238, 231, 218));
        jLabel9.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(238, 231, 218));
        jLabel9.setText("Stok");
        roundedPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 431, 111, 21));

        txtkode.setBackground(new java.awt.Color(238, 231, 218));
        txtkode.setLineColor(new java.awt.Color(238, 231, 218));
        txtkode.setSelectionColor(new java.awt.Color(238, 231, 218));
        roundedPanel1.add(txtkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 171, 87, 21));

        txtnama.setBackground(new java.awt.Color(238, 231, 218));
        txtnama.setLineColor(new java.awt.Color(238, 231, 218));
        txtnama.setSelectionColor(new java.awt.Color(238, 231, 218));
        roundedPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 236, 173, 21));

        txtharga.setBackground(new java.awt.Color(238, 231, 218));
        txtharga.setLineColor(new java.awt.Color(238, 231, 218));
        txtharga.setSelectionColor(new java.awt.Color(238, 231, 218));
        roundedPanel1.add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 366, 173, 21));

        txtstok.setBackground(new java.awt.Color(238, 231, 218));
        txtstok.setLineColor(new java.awt.Color(238, 231, 218));
        txtstok.setSelectionColor(new java.awt.Color(238, 231, 218));
        roundedPanel1.add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 431, 87, 21));

        btnubah.setForeground(new java.awt.Color(136, 171, 142));
        btnubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_baseline-edit.png"))); // NOI18N
        btnubah.setText("Ubah");
        btnubah.setColor(new java.awt.Color(238, 231, 218));
        btnubah.setColorClick(new java.awt.Color(190, 184, 174));
        btnubah.setColorOver(new java.awt.Color(214, 207, 196));
        btnubah.setcornerRadius(15);
        btnubah.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });
        roundedPanel1.add(btnubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 508, 125, 43));

        btnHapus.setBackground(new java.awt.Color(255, 75, 75));
        btnHapus.setForeground(new java.awt.Color(238, 231, 218));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo-trash.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setColor(new java.awt.Color(255, 75, 75));
        btnHapus.setColorClick(new java.awt.Color(190, 184, 174));
        btnHapus.setColorOver(new java.awt.Color(214, 207, 196));
        btnHapus.setcornerRadius(15);
        btnHapus.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        roundedPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 508, 125, 43));

        roundedPanel1.add(cbKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(693, 301, 173, 21));

        jPanel1.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 118, 1006, 583));

        cancelButton.setForeground(new java.awt.Color(238, 231, 218));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/material-symbols_batal.png"))); // NOI18N
        cancelButton.setText("Batal");
        cancelButton.setColor(new java.awt.Color(136, 171, 142));
        cancelButton.setColorClick(new java.awt.Color(108, 136, 113));
        cancelButton.setColorOver(new java.awt.Color(122, 153, 127));
        cancelButton.setcornerRadius(15);
        cancelButton.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1118, 744, 130, 49));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        Connection conn = new koneksi().getConnection();

        String sql = "update barang set nama=?,kategori=?,harga=?,stok=? where kode_barang='"+txtkode.getText()+"'";

        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtnama.getText());
            stat.setString(2, cbKategori.getSelectedItem().toString());
            stat.setString(3, txtharga.getText());
            stat.setString(4, txtstok.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
//            kosong();
            txtnama.requestFocus();

            conn.close();
            stat.close();
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal disimpan, pesan error: "+e);
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        try {
            // Mengatur look and feel menjadi Nimbus
            UIManager.LookAndFeelInfo[] looks = UIManager.getInstalledLookAndFeels();
            for (UIManager.LookAndFeelInfo look : looks) {
                if ("Nimbus".equals(look.getName())) {
                    UIManager.setLookAndFeel(look.getClassName());
                    break;
                }
            }

            // Buat objek JFrame baru
            JFrame formBarang = new table_model.barang();

            // Tampilkan JFrame baru
            formBarang.setVisible(true);

            // Tutup jendela saat ini
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    Connection conn = null;
    try {
        conn = new koneksi().getConnection();

        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data barang ini?", "Hapus Data Barang", JOptionPane.YES_NO_OPTION);
        if (ok == JOptionPane.YES_OPTION) {
            conn.setAutoCommit(false);

            // Hapus data terkait dari tabel pembelian
            deleteRelatedPembelian(conn, id);

            // Hapus data terkait dari tabel detail_penjualan
            deleteRelatedDetailPenjualan(conn, id);

            // Setelah data terkait dihapus, baru hapus data barang
            String deleteBarangSql = "DELETE FROM barang WHERE id = ?";
            try (PreparedStatement deleteBarangStat = conn.prepareStatement(deleteBarangSql)) {
                deleteBarangStat.setInt(1, id);
                int rowsAffected = deleteBarangStat.executeUpdate();

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Data barang berhasil dihapus");
                    conn.commit();
                } else {
                    JOptionPane.showMessageDialog(null, "Data barang tidak ditemukan");
                }
            } catch (SQLException e) {
                conn.rollback();
                throw e;
            } finally {
                conn.setAutoCommit(true);
            }

            // Refresh tampilan atau tindakan lain setelah penghapusan
            // refreshTableBarang();
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal menghapus data barang: " + e.getMessage());
        e.printStackTrace();
    } finally {
        try {
            if (conn != null) {
                conn.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    try {
  
    UIManager.LookAndFeelInfo[] looks = UIManager.getInstalledLookAndFeels();
    for (UIManager.LookAndFeelInfo look : looks) {
        if ("Nimbus".equals(look.getName())) {
            UIManager.setLookAndFeel(look.getClassName());
            break;
        }
    }

  
    JFrame tableModelBarang = new table_model.barang();
    tableModelBarang.setVisible(true); 
    this.dispose(); 
} catch (Exception ex) {
    ex.printStackTrace();
}

    }//GEN-LAST:event_btnHapusActionPerformed
private void deleteRelatedPembelian(Connection conn, int idBarang) throws SQLException {
    String deletePembelianSql = "DELETE FROM pembelian WHERE id_barang = ?";
    try (PreparedStatement deletePembelianStat = conn.prepareStatement(deletePembelianSql)) {
        deletePembelianStat.setInt(1, idBarang);
        deletePembelianStat.executeUpdate();
    }
}

private void deleteRelatedDetailPenjualan(Connection conn, int idBarang) throws SQLException {
    String deleteDetailPenjualanSql = "DELETE FROM detail_penjualan WHERE id_barang = ?";
    try (PreparedStatement deleteDetailPenjualanStat = conn.prepareStatement(deleteDetailPenjualanSql)) {
        deleteDetailPenjualanStat.setInt(1, idBarang);
        deleteDetailPenjualanStat.executeUpdate();
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RincianDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RincianDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RincianDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RincianDataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException ignored) {
            Toolkit.getDefaultToolkit().beep();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            ex.printStackTrace();
            return;
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RincianDataBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom_palette.RoundedButton btnHapus;
    private custom_palette.RoundedButton btnubah;
    private custom_palette.RoundedButton cancelButton;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private custom_palette.RoundedPanel roundedPanel1;
    private custom_palette.RoundedTextField txtharga;
    private custom_palette.RoundedTextField txtkode;
    private custom_palette.RoundedTextField txtnama;
    private custom_palette.RoundedTextField txtstok;
    // End of variables declaration//GEN-END:variables

}
